# xplat.yaml - Package manifest for xplat ecosystem
apiVersion: xplat/v1
kind: Package

name: plat-cms
version: main
description: Cross-platform CMS based on SpurtCMS
author: joeblew999
license: MIT

# Processes for process-compose
processes:
  postgres:
    command: docker compose up postgres
    port: 5432
    readiness_probe:
      exec:
        command: pg_isready -h localhost -p 5432

  cms:
    command: task go:run
    port: 8080
    depends_on:
      - postgres

# Environment variables
env:
  required:
    - name: DB_TYPE
      description: Database type (postgres or mysql)
      default: postgres
    - name: DB_HOST
      description: Database host
      default: localhost
    - name: DB_PORT
      description: Database port
      default: "5432"
    - name: DB_NAME
      description: Database name
      default: spurtcms
    - name: DB_USERNAME
      description: Database username
      default: postgres
    - name: DB_PASSWORD
      description: Database password
    - name: DB_SSL_MODE
      description: Database SSL mode
      default: disable
  optional:
    - name: AWS_ACCESS_KEY_ID
      description: AWS access key for S3 storage
    - name: AWS_SECRET_ACCESS_KEY
      description: AWS secret key for S3 storage
    - name: AWS_DEFAULT_REGION
      description: AWS region
    - name: AWS_BUCKET_NAME
      description: S3 bucket name for file storage
