#!/bin/bash
# Fetch blocks from SpurtCMS registry and save locally
# Usage: ./scripts/fetch-blocks.sh

set -e

BLOCKS_URL="https://superadmin.spurtcms.com/defaultblocklist/"
OUTPUT_DIR="seeds"
OUTPUT_FILE="$OUTPUT_DIR/remote-blocks.sql"

echo "Fetching blocks from SpurtCMS registry..."

# Fetch blocks as JSON
BLOCKS_JSON=$(curl -s "$BLOCKS_URL" -H "Accept: application/json")

# Check if we got valid JSON
if ! echo "$BLOCKS_JSON" | jq -e '.all_list' > /dev/null 2>&1; then
    echo "Error: Failed to fetch blocks or invalid response"
    exit 1
fi

BLOCK_COUNT=$(echo "$BLOCKS_JSON" | jq '.all_list | length')
echo "Found $BLOCK_COUNT blocks"

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Generate SQL file
cat > "$OUTPUT_FILE" << 'HEADER'
-- Remote Blocks from SpurtCMS Registry
-- Auto-generated by: ./scripts/fetch-blocks.sh
-- Source: https://superadmin.spurtcms.com/defaultblocklist/
-- Run with: xplat task db:seed-remote

HEADER

# Process each block
echo "$BLOCKS_JSON" | jq -c '.all_list[]' | while read -r block; do
    id=$(echo "$block" | jq -r '.Id')
    title=$(echo "$block" | jq -r '.Title' | sed "s/'/''/g")
    slug=$(echo "$block" | jq -r '.SlugName' | sed "s/'/''/g")
    channel_slug=$(echo "$block" | jq -r '.ChannelSlugname' | sed "s/'/''/g")
    description=$(echo "$block" | jq -r '.BlockDescription' | sed "s/'/''/g")
    content=$(echo "$block" | jq -r '.BlockContent' | sed "s/'/''/g")
    css=$(echo "$block" | jq -r '.BlockCss' | sed "s/'/''/g")
    icon=$(echo "$block" | jq -r '.IconImage' | sed "s/'/''/g")
    cover=$(echo "$block" | jq -r '.CoverImage' | sed "s/'/''/g")
    prime=$(echo "$block" | jq -r '.Prime')
    is_active=$(echo "$block" | jq -r '.IsActive')

    cat >> "$OUTPUT_FILE" << EOF
-- Block: $title ($slug)
INSERT INTO tbl_blocks (id, title, slug_name, channel_slugname, block_description, block_content, block_css, icon_image, cover_image, prime, is_active, tenant_id, created_on, created_by, is_deleted)
VALUES (
    $id,
    '$title',
    '$slug',
    '$channel_slug',
    '$description',
    '$content',
    '$css',
    '$icon',
    '$cover',
    $prime,
    $is_active,
    '1',
    NOW(),
    1,
    0
) ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    slug_name = EXCLUDED.slug_name,
    block_content = EXCLUDED.block_content,
    block_css = EXCLUDED.block_css,
    cover_image = EXCLUDED.cover_image;

EOF
done

# Add collection inserts
cat >> "$OUTPUT_FILE" << 'FOOTER'
-- Add all blocks to admin user's collection
INSERT INTO tbl_block_collections (user_id, block_id, tenant_id, is_deleted)
SELECT 1, id, '1', 0 FROM tbl_blocks WHERE is_deleted = 0
ON CONFLICT DO NOTHING;
FOOTER

echo "Generated: $OUTPUT_FILE"
echo "Run 'xplat task db:seed-remote' to import blocks"
